name: Build and publish
on:
  pull_request:
    types: [closed]
    branches:
      - stable

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged
    steps:
    - uses: actions/checkout@v2

    - name: Get yarn cache directory path
      id: yarn-cache-dir-path
      run: echo "::set-output name=dir::$(yarn cache dir)"

    - uses: actions/cache@v2
      id: yarn-cache
      with:
        path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
        key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-yarn-
    
    - name: Set up Node
      uses: actions/setup-node@v2
      with:
        node-version: '12'
        registry-url: 'https://registry.npmjs.org'

    - name: Install project
      run: yarn
    
    - name: Build contracts
      run: yarn compile

    - name: Set package version
      run: echo "VERSION=$(bash ./scripts/get_version.sh)" >> $GITHUB_ENV

    - name: Publish NPM package
      run: yarn publish contracts --access public --new-version $VERSION --verbose --no-git-tag-version
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
    
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ env.VERSION }}
        release_name: ${{ env.VERSION }}
