name: Build and test
on: [push, pull_request]

env:
  NODE_VERSION: 24
  PYTHON_VERSION: 3.9

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Node
      uses: actions/setup-node@v6
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'yarn'

    - name: Set up Python
      uses: actions/setup-python@v6
      with:
        python-version: ${{ env.PYTHON_VERSION }}
        cache: 'pip'

    - name: Install project
      run: yarn

    - name: Install slither
      run: pip3 install -r scripts/requirements.txt

    - name: Show slither version
      run: slither --version

    - name: lint
      run: yarn fullcheck
